**Utilização Básica do Módulo NumPy**

In [ ]:
#Importando o NumPy - se necessário, rodar o seguinte comando para instalar a biblioteca: !pip install numpy
import numpy as np

#Criando uma array diretamente com o método do módulo
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [ ]:
#Também é possível criar um array utilizando uma lista existente
lista1 = [1, 3, 5, 7]
arr2= np.array(lista1)
print(arr2)

[1 3 5 7]


In [ ]:
#Além disso, é possível criar um array com o método arange, passando o início, final e o passo
arr3 = np.arange(0, 50, 5)
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [ ]:
#O Método matrix também permite a criação de um array
lista2 = [2, 4, 6, 8]
arr4 = np.matrix(lista2)
print(arr4)

[[2 4 6 8]]


*A diferença básica entre o método array e matrix, é que o primeiro é mais voltado para tratar dados, enquanto o segundo para tratamentos matemáticos.*

**TRABALHANDO COM MATRIZES EM NUMPY**

In [14]:
#Por natureza, uma array simples é uma matriz unidimensional
arr5 = np.array([1, 2, 3])
print(arr5)
arr5.shape

[1 2 3]


(3,)

In [15]:
#Já quando criamos um array de uma lista de duas listas, teremos uma matriz bidimensional
arr6 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr6)
arr6.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
#Já uma matriz tridimensional, possui 2 elementos, cada qual com 2 linhas e 3 colunas, conforme o resultado do atributo SHAPE
lista3 = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
]
arr7 = np.array(lista3)
print(arr7)
arr7.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [19]:
arr8 = np.array([
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [11, 12, 13, 14, 15],
            [16, 17, 18, 19, 20]
        ],
        [
            [21, 22, 23, 24, 25],
            [26, 27, 28, 29, 30],
            [31, 32, 33, 34, 35],
            [36, 37, 38, 39, 40]
        ],
        [
            [41, 42, 43, 44, 45],
            [46, 47, 48, 49, 50],
            [51, 52, 53, 54, 55],
            [56, 57, 58, 59, 60]
        ]
    ],
    [
        [
            [61, 62, 63, 64, 65],
            [66, 67, 68, 69, 70],
            [71, 72, 73, 74, 75],
            [76, 77, 78, 79, 80]
        ],
        [
            [81, 82, 83, 84, 85],
            [86, 87, 88, 89, 90],
            [91, 92, 93, 94, 95],
            [96, 97, 98, 99, 100]
        ],
        [
            [101, 102, 103, 104, 105],
            [106, 107, 108, 109, 110],
            [111, 112, 113, 114, 115],
            [116, 117, 118, 119, 120]
        ]
    ]
])

print(arr8)
arr8.shape
arr8.ndim

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


4

**INSERÇÃO DO TIPO DE DADO**

In [ ]:
#Por padrão, o array faz o auto incremento do tipo de dado que está sendo inserido, porém, é possível forçar o tipo de dado que está sendo inserido. Ex.:
z = np.array([1, 2], dtype = np.float64)

#No exemplo acima, os dados são do tipo int, mas passaram a ser tipo float devido o valor de dtype ter sido informado na passagem dos dados.

**FATIAMENTO DE ARRAYS**

In [22]:
#Fatiamento de Arrays

arr9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr9)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr9[2,1])
print(arr9[:2,2])
print(arr9[0:2,1])

8
[3 6]
[2 5]


*Basicamente, no fatiamento de matrizes, é preciso indicar a linha e coluna (dimensões da matriz) separados por vírgula ([2,3]), para que um dado valor seja retornado*

*No caso dos exemplos ([:2,2] e [0:2,1]) o fatiamento está selecionando a partir da linha 0 até a 2 os elementos da coluna de indice 2 ou 1, dependendo do exemplo*